# Generated by Django 4.2.7 on 2023-11-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_i18n_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
